version: '3.5'
services:
  php_cli:
    build:
      context: ../php_cli
      dockerfile: Dockerfile
    container_name: returnnull_php_cli
    working_dir: /var/www/html
    volumes:
      - ./../../code:/var/www/html
    environment:
      - VHOST=localhost